---
title: "2.1 Skillcheck"
author: Tyler, Mo, Clara [Sec1]
output: html_document
---
```{r}
library(tidyr)
library(tidyverse)
library(janitor)
library(readxl)
library(ggplot2)
library(viridis)
library(viridisLite)
library(reshape2)
```

```{r}
#RASTER

# How to transform data according to pivot_longer()
data("volcano")
volcano <- data.frame(x = seq(1:nrow(volcano)), data.frame(volcano))
volcano.long <- pivot_longer(volcano, cols=!x, 
                             names_to = "y", names_prefix = "X", 
                             values_to = "elevation", 
                             names_transform = list(x = as.numeric,
                                                    y = as.numeric))
ggplot(volcano.long, aes(x, y)) +
  geom_raster(aes(fill = elevation)) + scale_fill_viridis_c()
```

```{r}
# Transform data using melt() in reshape2

data("volcano")
volcano_df <- melt(volcano)
colnames(volcano_df) <- c("lattitude", "longitude", "elevation")

data=volcano_df
ggplot(volcano_df, aes(lattitude, longitude)) +
  geom_raster(aes(fill = elevation)) + scale_fill_viridis_c()


```


```{r}
#TILE


volcano_df <- melt(volcano)
colnames(volcano_df) <- c("lattitude", "longitude", "elevation")

data=volcano_df
ggplot(volcano_df, aes(lattitude, longitude)) +
  geom_tile(aes(fill = elevation)) + scale_fill_viridis_c()


```

```{r}
#contour
#note, reshape2 and ggplot2 libraries open above

volcano_df <- melt(volcano)

colnames(volcano_df) <- c("Lattitude", "Longitude", "Elevation")

ggplot(volcano_df, aes(Lattitude,Longitude)) +
  
    geom_contour(aes(z=Elevation, col = ..level..)) 

```

